-- CREATE TABLE users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     email VARCHAR(255) NOT NULL UNIQUE,
--     age INT,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );
-- INSERT INTO users (name, email, age) VALUES
-- ('Alice Johnson', 'alice.johnson@example.com', 24),
-- ('Bob Smith', 'bob.smith@example.com', 31),
-- ('Charlie Lee', 'charlie.lee@example.com', 19),
-- ('Diana Patel', 'diana.patel@example.com', 27),
-- ('Ethan Brown', 'ethan.brown@example.com', 35),
-- ('Fiona Clark', 'fiona.clark@example.com', 22),
-- ('George Miller', 'george.miller@example.com', 41),
-- ('Hannah Wilson', 'hannah.wilson@example.com', 29),
-- ('Ivan Petrov', 'ivan.petrov@example.com', 34),
-- ('Julia Roberts', 'julia.roberts@example.com', 26),
-- ('Kevin Nguyen', 'kevin.nguyen@example.com', 21),
-- ('Laura Garcia', 'laura.garcia@example.com', 33),
-- ('Michael Adams', 'michael.adams@example.com', 38),
-- ('Nina Rossi', 'nina.rossi@example.com', 25),
-- ('Oscar Lopez', 'oscar.lopez@example.com', 28),
-- ('Priya Sharma', 'priya.sharma@example.com', 23),
-- ('Quentin Moore', 'quentin.moore@example.com', 45),
-- ('Rachel Kim', 'rachel.kim@example.com', 30),
-- ('Samuel Wright', 'samuel.wright@example.com', 36),
-- ('Tina Ahmed', 'tina.ahmed@example.com', NULL);
SELECT * FROM users